[variables]
NODE_ENV = "prod"

[phases.setup]
nixPkgs = ["nodejs_24", "yarn-1_x", "python3", "pkg-config", "gcc", "gnumake"]

[phases.install]
cmds = [
  "npm config set registry https://registry.npmmirror.com/",
  "yarn config set registry https://registry.npmmirror.com/",
  "yarn install --frozen-lockfile --network-timeout 600000"
]

[phases.build]
cmds = ["yarn build"]

[start]
cmd = "node build/app.js"
